# 🛒 UrbanCart E-commerce Data Analytics Project

## 📖 Introduction
UrbanCart is a growing online retail shop operating across multiple cities. This project focuses on transforming raw transactional data into actionable insights to drive business strategy, marketing decisions, and inventory optimization.

## 👤 My Role
As a **Data Analyst**, my responsibility is to:
- Increase revenue through data-driven decisions.
- Improve product bundling and recommendations.
- Understand customer purchasing behavior.
- Optimize inventory and payment methods.
## 🏗️ Database Architecture (ER Diagram)
Below is the logical structure of the UrbanCart database. It includes dimension tables (Customers, Products) and fact tables (Orders, OrderItems, Payments).

![ER Diagram](image/er_diagram.png)

## 🗂️ Data Dictionary
- **DimCustomers:** Customer demographics (customer_id, name, gender, City, email,created_at).
- **DimProducts:** Product catalog (product_id, product_name, category, unit_price, stock).
- **FactOrders:** Transaction headers (order_id, customer_id, order_date, status).
- **FactOrderItems:** Detailed order lines (order_item_iD, product_iD, Quantity,order_id).
- **FactPayment:** Payment transactions (payment_id, order_iD, method).

  ## 🛠️ Analysis Framework & Business Questions

The analysis is structured into five key pillars to provide actionable insights for UrbanCart's strategic growth:

### 1️⃣ Sales & Order Fundamentals
*Focuses on order trends, customer reach, and growth patterns.*
1. **Total Order Volume:** How many total orders has UrbanCart received so far?
2. **Customer Reach:** How many unique customers have placed at least one order?
3. **Geographic Distribution:** Which cities generate the highest number of orders?
4. **Customer Retention:** What percentage of customers have placed more than one order?
5. **Time-Series Analysis:** What is the monthly trend of total orders over time?

### 2️⃣ Revenue & Product Performance
*Focuses on financial health and product-level success.*
6. **Gross Revenue:** What is the total revenue generated by UrbanCart?
7. **Category Contribution:** Which product categories contribute the most to total revenue?
8. **Top Revenue Generators:** Which individual products generate the highest revenue?
9. **Transaction Metrics:** What is the Average Order Value (AOV) and Average Basket Size?

### 3️⃣ Inventory Management & Risk
*Focuses on stock optimization and sales-to-stock ratios.*
10. **Stock-Out Analysis:** Which products are at risk of stock-out due to high sales volume and low inventory?

### 4️⃣ Customer Behavior & Segmentation
*Focuses on who the customers are and how they buy.*
11. **High-Value Customers:** Which customers contribute the highest total revenue?
12. **Purchase Volume:** What is the average number of products purchased per order?
13. **Gender-Based Patterns:** Do male and female customers show different purchasing patterns by category?
14. **City-Wise AOV:** Which cities have the highest average order value?
15. **Customer Lifecycle:** How does customer purchasing behavior change over time since account creation?

### 5️⃣ Payment & Order Flow Insights
*Focuses on transaction efficiency and payment preferences.*
16. **Payment Popularity:** Which payment methods are used most frequently?
17. **Status Analysis:** Is there any relationship between payment method and order status?
18. **Regional Preferences:** Do certain cities prefer specific payment methods?
19. **Payment vs. Value:** Are higher-value orders associated with specific payment methods?

---

## 🚀 Key Insights & Results

![Total Orders](./image/p1.png)
![](./image/p2.png)
![](./image/p3.png)
![](./image/p4.png)
![](./image/p5.png)
![](./image/p6.png)
![](./image/p7.png)
![](./image/p8.png)
![](./image/p9.png)
![](./image/p10.png)
![](./image/p11.png)
![](./image/p12.png)
![](./image/p13.png)
![](./image/p14.png)
![](./image/p16.png)
![](./image/p17.png)
![](./image/p18.png)
![](./image/p19.png)
![](./image/p20.png)
![](./image/p21.png)
![s](./image/p23.png)
![](./image/p24.png)
---

## 🏁 Final Conclusion & Strategic Recommendations

Based on the comprehensive analysis of UrbanCart's transactional data, the following strategic actions are recommended to drive growth and efficiency:

### 1. Drive Digital Transformation
* **Dhaka Strategy:** Since **Dhaka** is the only city where **bKash (29)** usage surpasses **COD (27)**, launch exclusive "Digital-First" campaigns in the capital to reduce cash-handling risks.
* **MFS Partnerships:** Collaborate with **Nagad** for high-value promotions, as it consistently drives the highest average order value (nearly **490**).

### 2. Optimize Product Bundling for Revenue
* **High-Value Bundles:** Promote the **Miniket Rice (5kg) & Power Bank (10000mAh)** combination as a "Premium Family Bundle," as it is the top revenue generator (**58,450**).
* **Grocery Cross-Selling:** Automatically suggest **Peanut 500g** to customers adding **Potato 1kg** to their cart, leveraging the most frequent organic pairing (**22 times**).

### 3. Enhance Customer Basket Size
* **Debit Card Incentives:** Since **Debit Card** users purchase the most items per order (**avg 10.5+**), introduce "Volume Discounts" specifically for card payments to encourage bulk buying.
* **bKash Upselling:** Since **bKash** users currently have the lowest item count per order, implement "Add-on" suggestions at checkout to increase their basket size.

### 4. Inventory & Logistics Optimization
* **Regional Stocking:** Increase inventory of daily staples in **Barishal** and **Sylhet**, as these cities show the highest order volume and reliance on **COD**.
* **High-Demand Monitoring:** Closely monitor stock for **Potato**, **Milk**, and **Rice**, as these are core components of the most frequent product pairings.

---

## 🛠️ Tools Used
* **SQL:** Data extraction and complex joining of Fact and Dimension tables.
* **Excel:** Data visualization and Pivot analysis.
*  **Power Point:** Presenting the Project
* **Statistical Analysis:** Correlation of payment methods with order values.

---

## 🎯 Final Key Takeaways
* **Dhaka** leads in digital adoption, while **Barishal** and **Sylhet** dominate in COD volume.
* **Nagad** and **Credit Cards** are the preferred methods for high-value transactions.
* **Debit Card** transactions involve the highest number of items per order.
* The **Miniket Rice & Power Bank** combo is the most effective bundle for maximizing revenue.




